name: Casino
version: 1.0.0
main: com.minecraftcodex.casino.Main
api-version: '1.20'
author: Minecraftcodex
softdepend: [Vault, Citizens]
commands:
  casino:
    description: Opens a Casino game menu
    usage: /casino <slots|blackjack|poker|roulette|truthlie>
permissions:
  casino.admin:
    default: op
